# Generated by Django 2.1.7 on 2019-03-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('charges_included', models.BooleanField()),
                ('real_estate_type', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('furnished', models.BooleanField()),
                ('square', models.FloatField()),
                ('ges', models.IntegerField()),
                ('energy_rate', models.IntegerField()),
            ],
        ),
    ]
