# Generated by Django 2.1.7 on 2019-03-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedPill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='owner_is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='charges_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='energy_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='ges',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='real_estate_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='square',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
