# Generated by Django 2.1.7 on 2019-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedPill', '0002_auto_20190328_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
