# Generated by Django 2.1.7 on 2019-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedPill', '0003_auto_20190328_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
