# Generated by Django 2.1.7 on 2019-03-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedPill', '0004_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_relevant',
            field=models.BooleanField(default=True),
        ),
    ]
