# Generated by Django 2.2 on 2019-04-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedPill', '0005_location_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
